name: Build
on:
  push:
  pull_request:

env:
  ci_source_dir: ${{ github.workspace }}/source-code
  ci_build_dir: ${{ github.workspace }}/cmake-build

jobs:
  Windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.ci_source_dir }}
          fetch-depth: 1
          submodules: recursive

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.21.x'

      - name: Generate
        shell: bash
        run: cmake -G 'Visual Studio 17 2022' -DCMAKE_BUILD_TYPE=RelWithDebInfo -B "${{env.ci_build_dir}}" -S "${{env.ci_source_dir}}"

      - name: Build
        shell: bash
        run: cmake --build "${{env.ci_build_dir}}" --config RelWithDebInfo

      - name: Test
        shell: bash
        run: |
          cd "${{env.ci_build_dir}}/RelWithDebInfo"
          ls
          ./a.exe
